name: Solary-Market
main: nuvemplugins.solarymarket.Main
version: 1.1
author: Sr_Edition
website: www.nuvemplugins.com
commands:
  mercado:
    description: "Para ver todos os comandos do plugin"
    aliases: [market]
    